### ISSUE TITLE
all APIs in Dashboard should be called every min 

### ISSUE THREAD

**Issue by RiskingTime** [MarkdaleMGMT/frontend-app#21]
data should be refreshed every minute

**Comment by RachelTWQ** [comment]
Hi there,

I am one of the candidates of part-time front-end developer role. I am currently working on the assignment that James gave me. I spent a day to go through the code and I would like to confirm some details about this code challenge. 
From the code challenge project, I was told to do Coding Challenge Admin Dashboard.
1.) It seems that there is no sign up endpoint being called on the web app. Is this part of the challenge? I don't seem to see it on the project tab. 

2.) From the way I see right now, it seems like there is mock data on the transaction table. I can add transactions to the web state of the application but not saving to the back end since there doesn't seem to the a post call  for inserting transaction request . I only see the Get request to load all existing transactions. So my question is if I am suppose to use the API to store and load transaction data? Or should I be storing in the redux state and changing it there.

3.) It seems there is a backend-node js server but I don't see any instructions for forking that part. Is it something I need to be handling as well?

Thanks,
Rachel

**Comment by sanliverpool13** [comment]
We are supposed to refresh the data every minute even though the data is static? As part of the front-end challenge I was only told to fork the front-end app. I am not dealing with a node js server so what is the point of refreshing static data?

**Comment by ayeshah** [comment]
@RachelTWQ 
1. sign up is not part of the challenge, use "ayesha" as the username
2. you need to modify the transaction history table to fetch data from the appropriate API. the transactions are updated in the db when you trigger a withdrawal, deposit, global update, etc.... you dont need to write to the db. just store the transaction in the application state
3. your only tasks are to modify the existing codebase and integrate with APIs for which the frontend-app repo and API documentation should be sufficient

**Comment by ayeshah** [comment]
@sanliverpool13 the coding challenge requires you to modify the code to replace static data with data fetched from APIs and refresh this data every minute

**Comment by sanliverpool13** [comment]
Which APIs? There is no API available in the front-end code? And we are not provided with any backend stuff for this challenge? Am I missing something or is this code incomplete?

**Comment by ayeshah** [comment]
@sanliverpool13 each component gets data from a certain API. Refer to the API documentation section  in the [Orientation Guide](https://github.com/MarkdaleMGMT/frontend-app/wiki/Orientation). For example, transaction history table with use transaction history API

**Comment by sanliverpool13** [comment]
I see. Transaction History table is pretty obvious since there is a transaction history request in 'Multi Investments, Multiple Currencies' API. What about the Chart table and the Line Chart View? I understand that the Doughnut chart and the line chart view will represent the same data from looking at the design in the 'Adobe XD Design'. But what are the requests for those? The naming of the requests and the data in 'Multi Invesments...' API is a bit confusing.

**Comment by ayeshah** [comment]
@sanliverpool13 the API required is commented on the particular issue. If its still unclear, please comment on the specific issue.

**Comment by w1098819013** [comment]
Hi, I was assigned with the coding challenge. When calling the APIs, I am seeing a lot more user accounts in the response than in the mock-data provided in the code. Hence while updating, do all data get rolled to the front? Or do I have to update according to the account description?

(i.e update accounts with description: investment account, but leave those with description:user accounts)

Also, there isn't any information about what type of data some columns represent. For example, in the line chart, first column, there were names with "Clam-Miner, Just-Dice, Gold....", they seem like currencies, however, after issuing some requests to the server, the response body includes some investment accounts with similar names.

**Comment by w1098819013** [comment]
In addition, when npm start is ran, the application demands signin info, which I do not have, and hence making viewing the updates impossible, are there any ways around it?
