### ISSUE TITLE
User Dashboard Page: Populate doughnut chart with total balance for each investment owned by the user

### ISSUE THREAD

**Issue by RiskingTime** [MarkdaleMGMT/frontend-app#9]

**Comment by ayeshah** [comment]
Use Get User Balance API: 
https://documenter.getpostman.com/view/1176933/S17qR95n?version=latest#d6326c1f-f061-4f1f-9930-e48228b26dba

**Comment by dev-iamcrystal** [comment]
Hello,

I am one of the candidates of part-time front-end developer role. I am currently working on the assignment that James gave me. The tasks are required to use your APIs but I cannot see your postman api document page. 

The pages were accessible until just now, but it suddenly says 404 error. 
Please let me know. Thank you.

- SuJeong Na

**Comment by ayeshah** [comment]
Hi,  can you try this link again : https://documenter.getpostman.com/view/1176933/S17qR95n?version=latest ?

**Comment by dev-iamcrystal** [comment]
Hi @ayeshah,

still cannot access - 404 error.

**Comment by ayeshah** [comment]
@dev-iamcrystal that's weird I can access it fine ...
try this link as well https://documenter.getpostman.com/view/1176933/S17qR95n

**Comment by dev-iamcrystal** [comment]
Hello, 

both work now. Thank you!
Have a nice day!

**Comment by dev-iamcrystal** [comment]
Hello ayeshah,

I have another question.
There are three APIs  

 1. TRANSACTION METHODS (http://142.93.150.161/) 
      - https://documenter.getpostman.com/view/1176933/RznELeSs?version=latest#28e789eb-77be-44d2-acc7-d90328ee66a3
      - all the methods are POST
 2. FRONTEND API(http://178.128.233.31/frontend/)
      - https://documenter.getpostman.com/view/1176933/SVSLrU7M?version=latest#b1985de3-13b9-46ac-9268-1f59a33ba1d0
      - has both GET and POST methods
 3. MULTI INVESTMENTS, MULTIPLE CURRENCIES (http://142.93.148.141/backend/)
      - https://documenter.getpostman.com/view/1176933/S17qR95n?version=latest#d6326c1f-f061-4f1f-9930-e48228b26dba
      - all the methods are POST

I have been trying to pull data with both POST and GET from all the APIs for several times. The first and second APIs works for me, but the third one(backend api) keep giving me following error: 

 [dashboard:1 Access to fetch at 'http://142.93.148.141/backend/users/balance' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.]

Is the third API suppose to block users who don't have permission since it responses with live data? Or maybe the syntax was wrong, should I try to pull the data with different way? Please let me know. 
I will just keep working with first and second APIs until getting an answer.

Thank you! 

Best regards, 
Sujeong Na

**Comment by ayeshah** [comment]
@dev-iamcrystal  you need to change the IP to that provided to you in the coding challenge: 178.128.233.31. This should be done for all APIs being called by the app.

**Comment by dev-iamcrystal** [comment]
Hello Ayeshah,

I have been working on the project with calling your api. I found the fact that the apis url on the Postman should be updated: 
https://documenter.getpostman.com/view/1176933/S17qR95n?version=latest#d6326c1f-f061-4f1f-9930-e48228b26dba

Currently, 
you have _http://142.93.148.141/backend/method_ on the Postman, 
I think it should be without "/**backend**" - _http://142.93.148.141/method_

Thank you.
Sujeong Na

**Comment by ayeshah** [comment]
@dev-iamcrystal  you need to use the correct IP: 78.128.233.31 as specified in the coding challenge 
The API documentations are correct otherwise
